Java Interop German Idealism
- Java Interop: Support full access to Gosu from Java
-- Generate Java stubs for Gosu types on demand from our JavaParser
--- Only generate stubs when the Java compiler requires it and only for types referenced from Java

-- Compiler generates bridge methods for constructors of Generic Gosu classes
--- bridge constructor methods remove type arguments and forward bounding types to real constructor
--- Gosu Java Stub generates constructors for these bridge methods (so Java doesn't have to provide them)

-- Generic functions do not reify type variables unless the body of the function requires it
--- new 'reified' modifier required to reify function
--- new parse errors for expressions involving reification
--- new parse errors for mismatched 'reified' modifier with overridden methods
--- the change helps some with performance related to unnecessary type reification management otherwise generated by the compiler
--- Java Interop: Java can directly call/override generic methods that are not reified

-- Load JavaClassInfo from source at runtime, if Java source is present.
-- A source-based JavaClassInfo can still dynamically load its bytecode via dynamic compilation
-- e.g., JavaSourceType classinfo implements getBackingClass() by Class.forName() which will load bytecode
dynamically via our Url handler which compiles the source

-- Modified BlockType backend behavior to differentiate between void and non-void return types
--- void return erased to IProcedureXxx interfaces,  non-void IFunctionXxx
--- Java Interop: Java is otherwise not compatible with the use-case involving passing a void-return lambda to an IFunctionXxx, need IProcedureXxx
--- Perf: slight improvement, avoids null-return / popping management

-- IFunctionXxx and IProcedureXxx are now Functional Interfaces
--- this helps with Java Interop; call-compatible with Java source using lambdas
--- Generified the interfaces so Java call-sites can infer types

- Misc
-- Unified usages of various versions of LazyStringSourceFileHandle classes as one
-- Handle NoClassDefFoundError resulting from tool.jar missing when JavaParser is invoked from a gw test initializing
-- Turn off JavaTypeExtensions bullshit in standard Gosu