(Squashed) 167 commits' worth of contributed tests
Adding basic tests for new annotation type - IDE-2634, IDE-2632, IDE-2631, IDE-1416

Add spec tests for IDE-1228 and GOSU-9

Add spec tests for IDE-1228 and GOSU-9

Add spec tests for IDE-2627

Add spec tests for IDE-1613

Add spec tests for IDE-1845

Merge remote-tracking branch 'upstream/spec' into spec

Break single method in two since the parser from analyzer stops at first error.

Break single method in two since the parser from analyzer stops at first error.

Add spec tests for IDE-2968 - allow HashMap Compile time constant

Fix test by not using primitives as type arguments.

name block parameter to fix test

Split test class in two.

Improve dimension tests.

Fix test for IDE-1606 to include //##issuekeys

Fix test for IDE-2985

Mark comparisons between a dimensions and a number as errors

Make these dimension tests reflect the current behavior of Gosu when comparing dimensions with numbers

Add more test cases concerning meta types.

Uncommenting the case for IDE-3016

IDE-339: Implement verifications for compound types in type parameter bounds.

Add a test for Java-based properties with raw types.

Add test for IDE-2148 - Do not allow override static methods

Added some seed cases for default constant values.

Adding tests for PL-33465

Add a few more counpound type test cases.

Fixing tests for PL-33465 to have Errant_ in the file name to avoid compile time issues

Adding tests for Checked Arithmetic !+, !-, !*

Add a test for method scoring in static inner classes that have similar-signature methods with difference only in boxed types.

Add some more metatype test cases

Remove KB comments

Add more test cases from IDE-2238

Add a few more dimension test cases

Adding 2 more cases for IDE-339

Splitting test for same name and same erasure cases

Adding tests for IDE-2240 and IDE-2251

Add a test case and remove one!

Add more tests for conditional expression type inference.

IDE-451: Add more tests for conditional expression type inference.

IDE-1194: Added more test cases

Rename test class and add one more test case

IDE-2110: Relational operators on comparable types.

IDE-2285: Add test

IDE-2279, IDE-2517: Added tests

a

Rename test back.

Move my dimension test out and simplify it.

Add main case for IDE-1194

IDE-3010: Semicolons should be allowed in switch statements

Adding more cases for IDE-2110

IDE-3012: Add a test for Infinity and NaN.

 IDE-3012: Add more tests for Infinity and NaN.

Adding test for covariant method overriding PL-32029

Adding test for IDE-1178. Structural typing.

Adding test for IDE-1259. Structural typing.

Fixing tests so that method and properties actually come from enhancments - IDE-1180

Adding tests for Structural Typing involving Generics

Adding tests for Shadowing: private fields of nested parent and child class

Fix test by removing bad import.

Fix test and add more for IDE-2196

Add test for protected enhancement defined in different package

Added test for static inner class attempting to extend non-static inner class.

Add another use case to Errant_DimensionArithmetic.gs: can't do math on non-final classes.

Adding tests for IDE-2358

Adding tests for IDE-2265 - raw return type

Test for IDE-3322 Studio cannot match Enum constructor to an inferred block

Test for IDE-3070 Ferrite : Gosu error highlighting : IDE parser is whitespace-sensitive on a multiple line Gosu return statement.

Adding tests for IDE-3475 - Dynamic type with no import statement

Since dynamic package has been added to the list of default packages, this should work fine

Fix compilation error:

[ERROR] /home/ubuntu/gosu-lang/gosu-test/src/test/gosu/gw/specContrib/enums/MatchInferredBlockConstructor.gs:[3,6] error: The class name gw.specContrib.enums.Foo does not correspond with the file gw.specContrib.enums.MatchInferredBlockConstructor.

Update annotations and add missing override keywords so that tests pass on open source gosu.
Modify BaseVerifyErrantTest.gs so that a bad annotation doesn't throw NPE.

Undo erroneous edit.

Add test for parsing metatypes, especially literal metatypes.

Add test for duplicate (inner) class.

Fix name of class in new test

Adding tests for IDE-3179 - Uses statement should not be allowed inside a method

Adding more tests for IDE-3179 - Uses statement should not be allowed inside a method

IDE-3016 - Adding more tests as the bug has been fixed. for(..) requires in clause except in case of IntegerInterval

IDE-2987 - Adding tests for intervals - boolean and custom types

IDE-3031 - Should report UNREACHABLE STATEMENT for switch with all enum values

IDE-3646 - Adding tests for intervals in for/foreach

IDE-3017 - Adding more tests for index and iterator should not be writable in for loop.

Also added tests for the above case in nested for loop

Tests for IDE-3641 method call with (args) on next line

Adding tests for IDE-2807 - assert is a reserved keyword

Adding tests for IDE-3609 - enhanced type should use all of enhancements type params

Adding more tests for IDE-3609 - enhanced type should use all of enhancements type params

Adding tests for IDE-3447 - List cannot be initialized as Gosu behavior is changed now
var x = new List() //not valid now

Improve dimension tests.

a

Rename test back.

Dimensions: fix a test and add another one.

Test for IDE-3322 Studio cannot match Enum constructor to an inferred block

Fix compilation error:

[ERROR] /home/ubuntu/gosu-lang/gosu-test/src/test/gosu/gw/specContrib/enums/MatchInferredBlockConstructor.gs:[3,6] error: The class name gw.specContrib.enums.Foo does not correspond with the file gw.specContrib.enums.MatchInferredBlockConstructor.

Undo erroneous edit.

Added test for IDE-3045

Missed a rename, I think.

Fix annotation errors so that the tests pass in gosu-lang

Adding tests for IDE-2317 - empty index array access, map access should show error

Adding tests for IDE-2356 - remove aliased types - Bean, DateTime

Adding tests for IDE-2163 - IDE doesn't show error for boolean 'and' and 'or' operators when one of operands is Dynamic and another is non-boolean

Adding tests for IDE-2963 - Ferrite : Should not allow importing same name type as the class name
and moving one test to the right package

Fixing tests for IDE-2618 - interface's static method can be accessed as super[Interfacename].methodName( ), i.e. the way default methods are accessed. It is expected behavior as per Gosu team

Adding tests for IDE-1502 - Ferrite : OS Gosu : Error should be shown when 'final' modifier applies to 'enum' type

IDE-2041 - IDE: doesn't show error when making compound type with Dynamic

Adding tests for IDE-3725 -  Allow using 'property' keyword in package name or uses statement

Adding tests for IDE-3717 - Studio not inferring Dynamic type correctly

Adding tests for IDE-1285 -Should show error if a function in interface has a default return value

Adding tests for IDE-3770 - Dynamic types assignability involving Dynamic type params

Added Tests for IDE-2327, for control flow analysis of switch statement

Add test for IDE-3772 Uses confuses scope for Gosu Editor

Add test for explicitly declared and named lambda blocks that call themselves recursively

Add 2 new cases to Errant_BlocksRecursiveCall.gs

Add one more way to specify an explicit block type

Note the case that fails due to IDE-3805

Added tests for IDE-2593

Adding tests for IDE-1852 and IDE-3760 - getter setter method calls on properties should not work

Adding tests for IDE-2902 - getters/setters in different Java (super-sub) classes and accessed in Gosu class

Fixing tests for IDE-1920, IDE-1908. Changing interface to class and interface to structure and adding test for annotation.

Adding tests for IDE-818 - Cyclic Inheritance

Add new test for Type to Type assignment, and treating Type<Object> like raw Type in subsitutors.

Add test for IDE-3611

Remove bogus package name

Add correct package statement

Add an edge case test of IDE-3611

Add uses for IType

Put space after ## before issuekeys

Add test for IDE-3615 x.Class

Add test for IDE-3642

Fix test annotations

Adding tests for IDE-535 - Ferrite : OS Gosu : Should not report error when the super class function name is same as the subclass constructor name.

Adding tests for IDE-1821 - for multiple default params in super constructor

Test for IDE-3948, Quoted text in a scriptlet.

Fixes (1) to Errant_StringTemplates.gs

Errant characters on line 1
Really should use semicolon, not \n

Fixes (2)

Add more tests for IDE-3956

Adding tests for IDE-3956 - Allow Gosu strong keywords as the intermediate package name

Add test cases for annotation argument

IDE-2637 Choose best method based on functional interface return type

Fix typo in test

Add tests for block return types and function to interface method scoring

Added a few cases

Fix test Errant_BlocksMixedReturnTypeCheck.gs

Add 2 more cases to lambda return test

Add test for IDE-1330 : Ferrite : Blocks : Parser should show error if interface method returns void but block returns something

Add test for IDE-2476 : Make direct access of MetaType features an error

Fixing Tests: Field name conflicting with local variable name

Add test for IDE-1772 when same lambda returns 0 and null

Fix test l14 to add issuekeys for l14

Add another test for missing return, and refine highlighting on returns

Fix tests Errant_BlocksBasics.gs and FunctionToInterfaceMethodScoring.gs

Fix Errant_BlocksBasics.gs accounting for backward compatible lambda

Adding tests for IDE-4053 - private static function when qualified with Class name should not show error in the same class.

IDE-1549 Errant Exit from finally block

Add to Errant_IfTypeNarrowing.gs for IDE-3196

Add more to Errant_IfTypeNarrowing.gs for IDE-3196

Add missing uses in Errant_IfTypeNarrowing.gs

Add test for IDE-4028 to Errant_IfTypeNarrowing.gs

Add uses java.math.BigDecimal to Errant_IfTypeNarrowing.gs

Added more tests for IDE-4048

Adding tests for IDE-4083 - Infer type from component type when type casting in methodCallExpression

Adding one more tests for IDE-4083 - Infer type from component type when type casting in methodCallExpression

Adding tests for IDE-4091 - typecasting + arrays and collection initializers

Added more tests for IDE-4091

Adding tests for IDE-4130 - literal metatype's type should be inferred correctly and should not resolve property Backing Class

Fixing erroneous issuekey I had added in Errant_CastAssignment in previous commit.

Add test for IDE-4164 Bad function declaration in enhancement on interface gives java.lang.VerifyError - should be detected during compilation

Fix up the I3 test

Make tests pass on mvn